In [1]:
import requests
import json
import pandas as pd

# Change these values for different dates
year = "2022"
month = "4"
day = "12"
hour = "12"
minute = "30"
second = "0"

site = f'https://api.data.gov.sg/v1/transport/carpark-availability?date_time={year}-{month.zfill(2)}-{day.zfill(2)}T{hour.zfill(2)}%3A{minute.zfill(2)}%3A{second.zfill(2)}'
print(site)
response_API = requests.get(site)
data = response_API.text
data = json.loads(data)
timestamp = data["items"][0]["timestamp"]
print(timestamp)

data = data["items"][0]["carpark_data"]
with open("EE4211data.json", 'w') as fp:
    json.dump(data, fp)
df = pd.read_json("EE4211data.json")
for heading in ("total_lots","lot_type","lots_available"):
    df[heading] = df["carpark_info"].apply(lambda x: x[0][heading])
df = df.drop(["carpark_info"], axis=1)
df

https://api.data.gov.sg/v1/transport/carpark-availability?date_time=2022-04-12T12%3A30%3A00

NumExpr defaulting to 8 threads.

2022-04-12T12:29:27+08:00

     carpark_number      update_datetime total_lots lot_type lots_available
0              HE12  2022-04-12T12:12:32        105        C              0
1               HLM  2022-04-12T12:12:42        583        C              0
2               RHM  2022-04-12T12:12:32        329        C            106
3              BM29  2022-04-12T12:12:32         97        C              1
4               Q81  2022-04-12T12:12:32         96        C              0
...             ...                  ...        ...      ...            ...
1961           B65M  2022-04-12T12:11:58        679        C            499
1962           B65L  2022-04-12T12:11:58          5        C              0
1963            BE3  2022-04-12T11:30:52        306        C            148
1964           BE3R  2022-04-12T11:30:52        195        C            150
1965            B8B  2022-04-12T12:11:45        249        C            172

[1966 rows x 5 columns]